### ISSUE TITLE
Update issue templates to multiple choice

### ISSUE THREAD

**Issue by thclark** [octue/twined#60]
Also over on https://github.com/octue/octue-sdk-python

Using an `ISSUE_TEMPLATE` folder and markdown files within it, it's possible to give the user an improved workflow, enabling them to choose between bug reports, feature requests and support requests.

The GCR Kaniko project is an example: https://github.com/GoogleContainerTools/kaniko/tree/master/.github/ISSUE_TEMPLATE

**Comment by cortadocodes** [comment]
I've now implemented this globally for the Octue organisation by adding the issue templates to the `.github` repository. It applies to all Octue repositories (not just public ones as I thought), and includes disabling blank issues.
