### ISSUE TITLE
Allow credentials to be required or not

### ISSUE THREAD

**Issue by thclark** [octue/twined#75]
### Use Case

If a service uses a credential in an optional way, it could be useful to have an `"isRequired": false|true` entry in the twine so that if a service is instantiated without this credential, its value shows up as `None` instead of the validation failing.

**PROS**
This would potentially allow services to behave differently based on their supplied credentials.

**CONS**
Controlling behaviour based on the credentials value is probably not a good idea because the credentials get obfuscated so it makes the processing pipeline harder to audit. Perhaps the best way is to apply a configuration value that dictates behaviour.

### Current state

All credentials are treated as required.

### Workaround

Set the credential to a known empty value like `` and use something like a configuration_value, e.g. `use_timezone_api: true|false` so the program flow is clear.

**Comment by cortadocodes** [comment]
I think we decided to keep requiring all credentials right @thclark? In which case we can close this issue

**Comment by thclark** [comment]
I think so but can’t remember the rationale...?

**Comment by cortadocodes** [comment]
I think basically what you said in this issue above ^

**Comment by thclark** [comment]
OK. **DECISION** if a credential can be supplied, it is required. Program control should rest on the input_values not the credential presence.
