### ISSUE TITLE
Address JSON schema deprecation warning

### ISSUE THREAD

**Issue by cortadocodes** [octue/twined#99]
The following warning is raised when running `tests.test_cli.TestStartCommand.test_start_command`:

```
DeprecationWarning: The metaschema specified by $schema was not found. Using the latest draft to validate, but this will raise an error in the future.
  cls = validator_for(schema)
```

**Comment by thclark** [comment]
Yes, we should. We're not (to my knowledge) anywhere using any incompatible features and beside, it's the responsibility of the individual strands to specify it so it wouldn't even be a breaking change for us, IMO.
